/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardPolicyPanel: typeof import('./components/CardPolicyPanel.vue')['default']
    CarrierWebsheetDialog: typeof import('./components/CarrierWebsheetDialog.vue')['default']
    DebugPanel: typeof import('./components/DebugPanel.vue')['default']
    DeviceAddDialog: typeof import('./components/DeviceAddDialog.vue')['default']
    DeviceAtTab: typeof import('./components/DeviceAtTab.vue')['default']
    DeviceCard: typeof import('./components/DeviceCard.vue')['default']
    DeviceConfigTab: typeof import('./components/DeviceConfigTab.vue')['default']
    DeviceDetailHeader: typeof import('./components/DeviceDetailHeader.vue')['default']
    DeviceDetailLoading: typeof import('./components/DeviceDetailLoading.vue')['default']
    DeviceEsimTab: typeof import('./components/DeviceEsimTab.vue')['default']
    DeviceListPanel: typeof import('./components/DeviceListPanel.vue')['default']
    DeviceOverviewTab: typeof import('./components/DeviceOverviewTab.vue')['default']
    DeviceUssdTab: typeof import('./components/DeviceUssdTab.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    ErrorBoundary: typeof import('./components/ErrorBoundary.vue')['default']
    ErrorState: typeof import('./components/ErrorState.vue')['default']
    FieldRow: typeof import('./components/FieldRow.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ListSkeleton: typeof import('./components/ListSkeleton.vue')['default']
    LoadingScreen: typeof import('./components/LoadingScreen.vue')['default']
    OperatorSelectionDialog: typeof import('./components/OperatorSelectionDialog.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    RefreshButton: typeof import('./components/RefreshButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusLight: typeof import('./components/StatusLight.vue')['default']
    SwitchDark: typeof import('./components/SwitchDark.vue')['default']
    TrafficAnalysisPanel: typeof import('./components/TrafficAnalysisPanel.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
